# Generated by Django 4.2 on 2025-02-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0005_alter_endpoint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('route', models.CharField(help_text='The endpoint route, e.g., /api/status', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this upstream does', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Upstream Definition',
                'verbose_name_plural': 'Upstream Definitions',
                'db_table': 'upstream_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUpstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_route', models.CharField(blank=True, help_text='Optional custom route for this service instance', max_length=255, null=True)),
                ('custom_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], help_text='Optional custom HTTP method', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstreams', to='instances.serviceinstance')),
                ('upstream_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='upstreams.upstreamdefinition')),
            ],
            options={
                'verbose_name': 'Service Upstream',
                'verbose_name_plural': 'Service Upstreams',
                'db_table': 'service_upstream',
                'ordering': ['service_instance', 'upstream_definition'],
                'unique_together': {('service_instance', 'upstream_definition')},
            },
        ),
    ]
