# Generated by Django 4.2 on 2025-02-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstreams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upstreamdefinition',
            options={'ordering': ['route'], 'verbose_name': 'Upstream Definition', 'verbose_name_plural': 'Upstream Definitions'},
        ),
    ]
