# Generated by Django 4.2 on 2024-10-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plant',
                'ordering': ['plant_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the filter is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='metadata.language')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('instance_name', models.CharField(max_length=255)),
                ('api_base_url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.plant')),
            ],
            options={
                'verbose_name': 'Service Instance',
                'verbose_name_plural': 'Service Instances',
                'db_table': 'service_instance',
                'ordering': ['instance_name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domain',
                'ordering': ['domain_name'],
            },
        ),
        migrations.CreateModel(
            name='APIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_control', to='tenants.serviceinstance')),
            ],
            options={
                'verbose_name': 'API Control',
                'verbose_name_plural': 'API Controls',
                'db_table': 'api_control',
                'ordering': ['service_instance'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_tenant_name_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceinstance',
            unique_together={('plant', 'instance_name')},
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('tenant', 'plant_name')},
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('domain_name',), name='unique_domain_constraint'),
        ),
    ]
