# Generated by Django 4.2 on 2024-10-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceinstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='plant',
        ),
        migrations.DeleteModel(
            name='APIControl',
        ),
        migrations.DeleteModel(
            name='ServiceInstance',
        ),
    ]
