# Generated by Django 4.2 on 2025-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_serviceinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
