# Generated by Django 4.2 on 2024-10-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_serviceinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('instance_name', models.CharField(max_length=255)),
                ('api_base_url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.plant')),
            ],
            options={
                'verbose_name': 'Service Instance',
                'verbose_name_plural': 'Service Instances',
                'db_table': 'service_instance',
                'ordering': ['instance_name'],
                'unique_together': {('plant', 'instance_name')},
            },
        ),
        migrations.CreateModel(
            name='APIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_control', to='instances.serviceinstance')),
            ],
            options={
                'verbose_name': 'API Control',
                'verbose_name_plural': 'API Controls',
                'db_table': 'api_control',
                'ordering': ['service_instance'],
            },
        ),
    ]
