# Generated by Django 4.2 on 2024-10-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this endpoint does', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='instances.apicontrol')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
                'db_table': 'endpoint',
                'ordering': ['route'],
                'unique_together': {('api_control', 'route', 'method')},
            },
        ),
    ]
