# Generated by Django 4.2 on 2024-10-26 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_alter_apicontrol_api_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('name', 'route')},
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='api_control',
        ),
    ]
