# Generated by Django 4.2 on 2024-10-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_alter_endpoint_unique_together_endpoint_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
