# Generated by Django 4.2 on 2025-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_alter_endpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the instance', null=True),
        ),
    ]
