# Generated by Django 4.2 on 2025-06-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_plant_description_plant_last_activity_plant_logo_url_and_more'),
        ('instances', '0006_serviceinstance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.tenant'),
        ),
    ]
